In [1]:
import cv2

img = cv2.imread("imori.jpg")
cv2.imshow("imori", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
import cv2
import numpy as np

In [3]:
img = cv2.imread("imori.jpg")

In [4]:
img.shape
#タテ、ヨコ、チャネル
#チャネルは(青、緑、赤)(B, G, R)の順

(128, 128, 3)

## 座標は原点左上、→x、↓y
## チャネルは(B, G, R)の順

In [5]:
img.dtype
#型(uint8は符号なしintの8bit、0～255)

dtype('uint8')

In [6]:
cv2.imshow("imori", img)#画像表示(window名, 画像)
cv2.waitKey(0)#キー入力を待つ(0だとずっと待つ)
cv2.destroyAllWindows()#windowを消す

In [7]:
#型を変える
_img = img.astype(np.float32)

cv2.imshow("_img", _img)
cv2.waitKey(0)
cv2.destroyAllWindows()

型が合ってない場合、うまく表示されない。よって、

### 画像いじるとき
1. cv2.imreadで読み込む  
2. 型を**一度np.float32など小数点型に変換する**  
3. 画像をいじる  
4. **画素が0未満のものは0, 255を超えたものは255に直す。(超重要！後述)**  
5. 型を**np.uint8に変換して表示・保存する。**  

In [8]:
img[20, 30]
#画素値はarray()
#.shapeで見た形状の多次元配列、(タテ、ヨコ、チャネルの3次元配列)

array([232, 178, 171], dtype=uint8)

# チャネルは(B, G, R)の順だよ！！！！

In [9]:
img[20, 30, 1]
# y=20, x=30, G, の画素値

178

## スライス

**スライス**を使うと、まとめて取り出せる。

In [10]:
img[20, 30:33]
# y=20, x=[30,32] 
#a:b で a <= v < b のvを取り出せる。リストとかのスライスと同じ。

array([[232, 178, 171],
       [209, 156, 153],
       [134,  85,  77]], dtype=uint8)

In [11]:
#画像の左上を黒にしてみる

img2 = img.copy()#画像のコピー
img2[:50, :50] = 0

cv2.imshow("", img2)
cv2.waitKey()
cv2.destroyAllWindows()

#### 4．画素が0未満のものは0, 255を超えたものは255に直す。について

画像をfloat32型にしてから、何か操作した時、  
uint8型は[0, 255]の範囲しかとらないので、  
この範囲から出た値は、uint8に戻すと、mod 256 に変換される。

In [12]:
img2 = img.copy()
img2 = img2.astype(np.float32)

img2[60:100, 60:100, 0] = 260
img2 = img2.astype("uint8")

print(img2[60:100, 60:100, 0])

cv2.imshow("", img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[4 4 4 ... 4 4 4]
 [4 4 4 ... 4 4 4]
 [4 4 4 ... 4 4 4]
 ...
 [4 4 4 ... 4 4 4]
 [4 4 4 ... 4 4 4]
 [4 4 4 ... 4 4 4]]


In [13]:
#画素値に値足す。オーバーしたら255にする。
img2 = img.copy()
img2 = img2.astype(np.float32)

H, W, C = img2.shape

for h in range(H):
    for w in range(W):
        img2[h, w, 0] += 120
        img2[h, w, 0] = min(img2[h, w, 0], 255)

print(img2[:, :, 0])
img2 = img2.astype("uint8")

cv2.imshow("", img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[252. 224. 220. ... 255. 254. 255.]
 [255. 237. 226. ... 255. 255. 255.]
 [255. 251. 239. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 227. 221. 213.]
 [255. 255. 255. ... 255. 239. 232.]
 [255. 255. 255. ... 255. 255. 236.]]


### 画像のコピー

In [14]:
img2 = img.copy()

### 画像の保存

In [15]:
cv2.imwrite("copy_img.jpg", img2)

True

### 練習
画像の左半分上のRとBを入れ替える。

In [26]:
import cv2
import numpy as np


img = cv2.imread("imori.jpg")

H, W, C = img.shape
img2 = img.copy()

img2[:H//2, :W//2] = img2[:H//2, :W//2, (2, 1, 0)]

cv2.imshow("", img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
print(img[0, 0, :])
print(img[0, 0, (2, 1, 0)])

[132  80  67]
[ 67  80 132]


In [19]:
#任意の領域を回転してみる
import cv2
import numpy as np


img = cv2.imread("imori.jpg")
img2 = img.copy()

a = img2[:100, :100]
img2[:100, :100] = a[::-1, ::-1]

cv2.imshow("", img2)
cv2.waitKey(0)
cv2.destroyAllWindows()